name: Security Header Analyzer Clone Count

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  get-clones:
    runs-on: ubuntu-latest

    steps:
      - name: Get Security Header Analyzer clone count
        env:
          GH_TOKEN: ${{ secrets.TRAFFIC_TOKEN }}
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            https://api.github.com/repos/AkhirahStrong/Security-Header-Analyzer/traffic/clones
